### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by minmingyu** [Zzh-tju/CIoU#20]
Hello author, iouLoss you proposed is very good at first, but when I added it to PyTorch halfway through the training,show: RuntimeError: CUDA Error: Device-side assert triggered. I am looking forward to your answer. Thank you!

**Comment by Zzh-tju** [comment]
you'd better put all the log here

**Comment by minmingyu** [comment]
> you'd better put all the log here
Thanks for your reply. I have solved this problem
